### ISSUE TITLE
Fetch mode doesn't work

### ISSUE THREAD

**Issue by michelle1574** [Samsung-Loki/Syndical#4] opened 2022-02-15 12:30 UTC
Command prompt output:
PS F:\syndical> ./Syndical.Application -m Fetch -M SM-A510F -r XEO
Device: SM-A510F/XEO
Connecting to FUS server...

Fetching firmware list ----------------------------------------   0% 00:00:00 \

Exception occured: Input string was not in a correct format.

**Comment by TheAirBlow** [comment] 2022-03-22 15:03
Duplicate of #6

**Closed as completed by TheAirBlow** 2022-03-22 15:03 UTC
